"""
config.py — Central configuration for the South Holland 3-30-300 viewshed pipeline.

Edit the values in this file before running any script — except for the
machine-specific settings just below, which you override in a local
`config_local.py` (gitignored, never committed) instead. See
config_local.example.py for a template.
"""

import csv
import datetime
import os
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
BASE_DIR             = Path(__file__).parent.parent
DATA_DIR             = BASE_DIR / "data"
RAW_DIR              = DATA_DIR / "raw"          # source data, never written to by the pipeline
INTERIM_DIR          = DATA_DIR / "interim"      # tiled / intermediate artefacts
PROCESSED_DIR        = DATA_DIR / "processed"    # final merged output

DEM_TILES_DIR        = INTERIM_DIR / "dem_tiles"       # per municipality, generated by 01_tile_dem.py
VIEWSHED_TILES_DIR   = INTERIM_DIR / "viewshed_tiles"  # per municipality, per-tile results

# ---------------------------------------------------------------------------
# Machine-specific settings — placeholders below are safe to publish.
# Override them per machine in config_local.py (gitignored). Do not put real
# paths here; they'll end up in git history.
# ---------------------------------------------------------------------------

# Root of the QGIS / OSGeo4W install that holds GDAL/OGR (nothing is pip-installed).
OSGEO4W_ROOT = r"C:\OSGeo4W"

# Source: one DEM (.tif) + one tree-position layer (.shp) per municipality,
# sharing the same basename (e.g. Papendrecht.tif / Papendrecht.shp).
VIEWANALYSE_DIR = Path(r"\\your-server\path\to\viewanalyse")

# Restrict processing to these municipalities (by file basename).
# Empty list = process every tif/shp pair found in VIEWANALYSE_DIR.
MUNICIPALITIES = ["Papendrecht"]

try:
    from config_local import *  # noqa: F401,F403 — machine-specific overrides
except ImportError:
    pass


def municipality_pairs():
    """Yield (name, dem_path, trees_path) for every tif+gpkg pair in VIEWANALYSE_DIR,
    filtered by MUNICIPALITIES when that list is non-empty.

    Trees are read from a GeoPackage (converted once from the original .shp —
    GeoPackage has a built-in R-tree spatial index, unlike a bare shapefile,
    which made per-tile bbox queries scan the whole file and dominated
    runtime on larger municipalities)."""
    wanted = set(MUNICIPALITIES) if MUNICIPALITIES else None
    for tif in sorted(VIEWANALYSE_DIR.glob("*.tif")):
        name = tif.stem
        if wanted is not None and name not in wanted:
            continue
        gpkg = VIEWANALYSE_DIR / f"{name}.gpkg"
        if gpkg.exists():
            yield name, tif, gpkg


def dem_tiles_dir(name: str) -> Path:
    return DEM_TILES_DIR / name


def tile_index_path(name: str) -> Path:
    return dem_tiles_dir(name) / "tile_index.json"


def viewshed_tiles_dir(name: str) -> Path:
    return VIEWSHED_TILES_DIR / name


def final_output_path(name: str) -> Path:
    return PROCESSED_DIR / f"{name}_viewshed.tif"


# ---------------------------------------------------------------------------
# Benchmark logging — one row per (municipality, stage) run, appended as it
# happens so partial data survives if a long multi-municipality run is
# interrupted. See scripts/generate_benchmark_report.py for turning this
# into BENCHMARKS.md.
# ---------------------------------------------------------------------------
BENCHMARK_LOG = BASE_DIR / "logs" / "benchmark.csv"
_BENCHMARK_FIELDS = ["timestamp", "municipality", "stage", "seconds", "tiles", "trees", "errors"]


def log_benchmark(municipality: str, stage: str, seconds: float, **extra) -> None:
    BENCHMARK_LOG.parent.mkdir(parents=True, exist_ok=True)
    is_new = not BENCHMARK_LOG.exists()
    with open(BENCHMARK_LOG, "a", newline="") as fh:
        writer = csv.DictWriter(fh, fieldnames=_BENCHMARK_FIELDS)
        if is_new:
            writer.writeheader()
        writer.writerow({
            "timestamp": datetime.datetime.now().isoformat(timespec="seconds"),
            "municipality": municipality,
            "stage": stage,
            "seconds": f"{seconds:.1f}",
            "tiles": extra.get("tiles", ""),
            "trees": extra.get("trees", ""),
            "errors": extra.get("errors", ""),
        })


# ---------------------------------------------------------------------------
# OSGeo4W / GDAL
# ---------------------------------------------------------------------------
GDAL_BIN     = os.path.join(OSGEO4W_ROOT, "bin")
GDAL_DATA    = os.path.join(OSGEO4W_ROOT, "share", "gdal")
PROJ_LIB     = os.path.join(OSGEO4W_ROOT, "share", "proj")

# Inject so that osgeo imports work from any Python environment
os.environ.setdefault("GDAL_DATA", GDAL_DATA)
os.environ.setdefault("PROJ_LIB",  PROJ_LIB)
if GDAL_BIN not in os.environ.get("PATH", ""):
    os.environ["PATH"] = GDAL_BIN + os.pathsep + os.environ.get("PATH", "")

# Try adding OSGeo4W's own Python site-packages so 'from osgeo import gdal' works
_osgeo_pydir = os.path.join(OSGEO4W_ROOT, "apps", "Python312", "Lib", "site-packages")
if os.path.isdir(_osgeo_pydir) and _osgeo_pydir not in sys.path:
    sys.path.insert(0, _osgeo_pydir)

# ---------------------------------------------------------------------------
# Viewshed parameters — matches the original QGIS "3" (trees-visible) analysis
# ---------------------------------------------------------------------------
MAX_DISTANCE      = 30.0   # metres — radius of each individual viewshed
OBSERVER_HEIGHT   = 1.7    # metres above DEM surface (default when no height column)
TARGET_HEIGHT     = 0.0    # metres above DEM surface for target pixels
CURVATURE_COEFF   = 0.0    # 0 = flat-earth; 0.85 = standard atmospheric refraction

# ---------------------------------------------------------------------------
# Tree layer settings
# ---------------------------------------------------------------------------
# Layer name inside the shapefile / database.  None = first layer auto-detected.
TREES_LAYER        = None

# Column that holds tree height (metres above ground).
# The source shapefiles have no such field, so every tree uses OBSERVER_HEIGHT.
TREES_HEIGHT_FIELD = None

# ---------------------------------------------------------------------------
# DEM tiling  (01_tile_dem.py)
# ---------------------------------------------------------------------------
# Size of each inner tile in pixels.  At 0.5 m DEM resolution, 1000 px = 500 m.
TILE_PIXELS    = 1000

# Buffer added on all four sides (pixels).
# Must satisfy: TILE_BUFFER_PX * pixel_size >= MAX_DISTANCE
# At 0.5 m resolution: 70 px * 0.5 m = 35 m  ✓
# This buffer is a "halo": trees within it are read for context so that inner
# pixels near a tile edge get correct contributions from a neighbour's trees,
# but only the inner window is ever written to output (02_compute_viewsheds.py
# crops to it) — this is what prevents seam artefacts at tile boundaries.
TILE_BUFFER_PX = 70

# GeoTIFF creation options for tiled output
TILE_CREATION_OPTIONS = ["COMPRESS=LZW", "TILED=YES", "BIGTIFF=IF_SAFER"]

# ---------------------------------------------------------------------------
# Processing
# ---------------------------------------------------------------------------
NUM_WORKERS  = 4     # parallel processes for tile-level parallelism
LOG_EVERY    = 5000  # log a progress line every N trees within a tile

# ---------------------------------------------------------------------------
# Output raster type
# ---------------------------------------------------------------------------
# UInt32 supports up to ~4 billion trees visible per pixel.
# Use UInt16 to halve the file size if you are sure counts stay < 65535.
OUTPUT_DTYPE = "UInt32"
